# Install packages
install.packages("dplyr")
install.packages("ggplot2")
install.packages("sf")
install.packages("terra")
install.packages("readr")
install.packages("jagsUI")
install.packages("coda")
#install.packages("ows4R")
# Load libraries
library("dplyr")
library("ggplot2")
library("sf")
library("terra")
library("readr")
library("jagsUI")
library("coda")
#library("ows4R")