name: Deploy R Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install R
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base

    - name: Copy vegetation_donana folder to server
      run: |
        scp -o StrictHostKeyChecking=no -i -r vegetation_donana ubuntu@ec2-16-171-0-75.eu-north-1.compute.amazonaws.com:/home/ec2-user/

    - name: Run R script on server
      run: |
        ssh -o StrictHostKeyChecking=no -i ubuntu@ec2-16-171-0-75.eu-north-1.compute.amazonaws.com 'Rscript /home/ec2-user/vegetation_donana/main_analyses_donana.r'
    - name: Verify GitHub Actions on server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-16-171-0-75.eu-north-1.compute.amazonaws.com 'echo "GitHub Actions are working again 1" > /tmp/github_actions_test.txt'
